resources/public/index.html, src-cljs/rmfu_ui/core.cljs, src-cljs/rmfu_ui/createarticle.cljs, src-cljs/rmfu_ui/profile.cljs
=> Add wireframes

src-cljs/rmfu_ui/core.cljs
@dviramontes helped me learn validation toolkit, this is the result. Connects to #2
=> Added input feild validation

src-cljs/rmfu_ui/core.cljs, src-cljs/rmfu_ui/createarticle.cljs, src-cljs/rmfu_ui/nav.cljs, src-cljs/rmfu_ui/profile.cljs, src-cljs/rmfu_ui/welcome.cljs
- refactors welcome component
- adds basic nav with .active link
connects to #28, closes #28 
visit: `/#/profile` to see the nav
=> adds basic <nav/>, refactors welcome component

src-cljs/rmfu_ui/nav.cljs
Fix #29, does not redirect main page to the sign-in
=> Add functionality to Logout button

src-cljs/rmfu_ui/about.cljs, src-cljs/rmfu_ui/core.cljs
=> Add About Page

project.clj, resources/public/css/style.css, src-cljs/rmfu_ui/about.cljs, src-cljs/rmfu_ui/admin.cljs, src-cljs/rmfu_ui/alert.cljs, src-cljs/rmfu_ui/article.cljs, src-cljs/rmfu_ui/core.cljs, src-cljs/rmfu_ui/createarticle.cljs, src-cljs/rmfu_ui/customfeed.cljs, src-cljs/rmfu_ui/feed.cljs, src-cljs/rmfu_ui/nav.cljs, src-cljs/rmfu_ui/profile.cljs, src-cljs/rmfu_ui/sign_in.cljs, src-cljs/rmfu_ui/sign_up.cljs, src-cljs/rmfu_ui/welcome.cljs, src/rmfu/auth.clj, src/rmfu/core.clj, src/rmfu/email.clj, src/rmfu/persistance.clj
closes #49
- refractors sign-in and sign-up into own components, removes unused deps
- table in admin component is more predictable when sorted
- user now stays signed-in for 3 days
- adds `<alert-component/>` to `sign-in`
=> As a User I would like to remain signed-in after signing-in

src/rmfu/core.clj
=> Enviro check

project.clj, src-cljc/rmfu/validation.cljc, src-cljs/rmfu_ui/createarticle.cljs, src/rmfu/persistance.clj
as titled
@codefordenver/core-contributors
=> adds article validation via Schema, front-end & back-end

project.clj, src-cljs/rmfu_ui/admin.cljs, src-cljs/rmfu_ui/alert.cljs, src-cljs/rmfu_ui/core.cljs, src-cljs/rmfu_ui/createarticle.cljs, src-cljs/rmfu_ui/nav.cljs, src-cljs/rmfu_ui/new_password.cljs, src/rmfu/auth.clj, src/rmfu/core.clj, src/rmfu/email.clj
=> Reset password token

resources/public/css/style.css, resources/public/index.html, resources/public/js/disqus.js, src-cljs/rmfu_ui/article.cljs
Some more work needs to be done here, including incorporating the DISQUS.refresh action, but comments now load on the article page.
connects to #11
=> Disqus integration

src-cljs/rmfu_ui/article.cljs, src-cljs/rmfu_ui/feed.cljs, src/rmfu/core.clj, src/rmfu/persistance.clj
Closes #16 
Wanted to open this now to start a conversation. This has basic functionality working. I'm not sure exactly what we want in the acceptance criteria for the story.
=> Add list view for articles

resources/public/js/disqus.js, src-cljs/rmfu_ui/article.cljs, src-cljs/rmfu_ui/core.cljs, src-cljs/rmfu_ui/feed.cljs
=> adds the #! to articles to URL, fixes DISQUS comments

externs.js, project.clj, resources/public/index.html, src-cljs/rmfu_ui/admin.cljs, src-cljs/rmfu_ui/profile.cljs, src-cljs/rmfu_ui/sign_in.cljs, src-cljs/rmfu_ui/utils.cljs, src/rmfu/auth.clj, src/rmfu/core.clj, src/rmfu/persistance.clj
- **adds article deletion table, closes #13**
- adds alert component to profile component
- move indexOf to utils
- adds externs.js
- adds data-table cdn deps
- refactors auth-user fn
- adds DELETE route
=> adds article deletion table, closes #13

resources/public/css/style.css, src-cljs/rmfu_ui/admin.cljs, src-cljs/rmfu_ui/article.cljs, src-cljs/rmfu_ui/feed.cljs, src/rmfu/core.clj, src/rmfu/persistance.clj
=> Display users by username instead of email

src/rmfu/core.clj, src/rmfu/email.clj, src/rmfu/persistance.clj
- closes #38 
- the mandrill template has also been updated
=> Adds email validation token

src-cljs/rmfu_ui/about.cljs
=> Fix minor typos

src-cljs/rmfu_ui/feed.cljs
=> fix for react warning

src-cljs/rmfu_ui/admin.cljs
=> adds link to article moderation table for admins

app.json, src/rmfu/core.clj, src/rmfu/email.clj
We want this configurable for domain changes, without requiring a new code commit
Connects to #68
=> Add HOSTNAME environment variable handling

src-cljs/rmfu_ui/admin.cljs, src-cljs/rmfu_ui/feed.cljs, src/rmfu/core.clj, src/rmfu/persistance.clj
=> adds basic pagination, closes #66

src-cljs/rmfu_ui/article.cljs, src/rmfu/core.clj
=> Allow general users to delete their articles

src-cljs/rmfu_ui/core.cljs, src-cljs/rmfu_ui/feed.cljs, src-cljs/rmfu_ui/sign_in.cljs, src-cljs/rmfu_ui/utils.cljs, src/rmfu/core.clj
=> adds resend-verify-email button, closes #87

resources/public/css/style.css, src-cljs/rmfu_ui/createarticle.cljs
=> Style updates
